### PR TITLE
readme: fix jedi's name

### PR DESCRIPTION
**Pull request by MarcoWorms**
image

### CODE REVIEW

**Review by vcapretz — APPROVED** [review]

**Comment by vitorsilvalima** [comment]
Forgive me Obi Wan Kenobi, I promise that I will never let the dark side make me miswrite you name again.

**Review by vitorsilvalima — APPROVED** [review]

**Comment by derekstavis** [comment]
Oes noes, I don't know what is the right but I believe in you 😂

**Comment by MarcoWorms** [comment]
The negotiations were short!

**Comment by MarcoWorms** [comment]
rofl

**Pull request merged**
